setTimeout(()=>{console.log("call the dominoz")
setTimeout(()=>{console.log("preparing order")
setTimeout(()=>{console.log("order ready")
setTimeout(()=>{console.log("pick by delivery boy for delivery")
setTimeout(()=>{console.log("delivered")},5000)
},1000)
},5000)
},2000)
},1000)